import Link from "next/link";
import { ArrowLeft, CalendarDays, CheckCircle2, Pencil, PlusCircle } from "lucide-react";
import { ReportSourceForm } from "@/components/reports/report-source-form";
import { ClientPageHeader } from "@/components/layout/client-page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { requireClient } from "@/lib/auth/guards";
import { SOURCE_STATUS_LABEL } from "@/lib/reports/constants";
import { formatReportDate, getDefaultReportDateInSaoPaulo, getTodayInSaoPaulo, isValidReportDate } from "@/lib/reports/date";
import { getClientLeadSources, getDailyCompletionStatus, getDailyReport, type LeadSource, type ReportSource } from "@/lib/reports/data.server";
import type { ReportSourceStatus } from "@/types";

type SearchParams = Promise<{ data?: string | string[]; origem?: string | string[]; sucesso?: string | string[] }>;

export default async function ReportsPage({ searchParams }: Readonly<{ searchParams: SearchParams }>) {
  const profile = await requireClient(); const parameters = await searchParams; const today = getTodayInSaoPaulo();
  const reportDate = typeof parameters.data === "string" && isValidReportDate(parameters.data) ? parameters.data : parameters.data === undefined ? getDefaultReportDateInSaoPaulo() : today;
  const [report, leadSources] = await Promise.all([getDailyReport(profile.clientId!, reportDate), getClientLeadSources(profile.clientId!, reportDate)]);
  const sourceId = typeof parameters.origem === "string" && leadSources.some((source) => source.id === parameters.origem) ? parameters.origem : null;
  const selectedSource = sourceId ? report?.sources.find((source) => source.lead_source_id === sourceId) : undefined;
  const selectedLeadSource = sourceId ? leadSources.find((source) => source.id === sourceId) : undefined;
  const isComplete = getDailyCompletionStatus(report?.sources ?? [], leadSources) === "FILLED";

  return <div><ClientPageHeader activePage="reportes" clientName={profile.client!.name} /><div className="mx-auto max-w-4xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">Reporte diário</h1><p className="mt-1 text-sm text-muted-foreground">Preencha as origens que se aplicarem ao dia. Dê prioridade à origem principal quando disponível.</p></div><form className="flex items-end gap-2" action="/reportes"><div><label className="text-sm font-medium" htmlFor="report-date-picker">Data do reporte</label><input className="mt-1 block min-h-11 rounded-md border bg-background px-3 text-base shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring md:text-sm" defaultValue={reportDate} id="report-date-picker" max={today} name="data" type="date" /></div><Button type="submit" variant="outline" className="min-h-11"><CalendarDays aria-hidden="true" className="mr-2 size-4" />Ver</Button></form></div>{sourceId && selectedLeadSource ? <Card><CardHeader><div className="flex items-center gap-3"><Button asChild variant="ghost" size="icon" aria-label="Voltar para as origens"><Link href={`/reportes?data=${reportDate}`}><ArrowLeft aria-hidden="true" className="size-4" /></Link></Button><div><CardTitle>{selectedLeadSource.name}</CardTitle><CardDescription>Reporte de {formatReportDate(reportDate)}</CardDescription></div></div></CardHeader><CardContent><ReportSourceForm reportDate={reportDate} sourceId={sourceId} source={selectedSource} /></CardContent></Card> : <><Card><CardHeader><CardTitle>Origens do reporte</CardTitle><CardDescription>{formatReportDate(reportDate)}. Preencha as origens que se aplicarem ao dia. Manter todas atualizadas é recomendado.</CardDescription></CardHeader><CardContent className="space-y-3">{leadSources.length ? leadSources.map((source) => <SourceCard key={source.id} leadSource={source} reportDate={reportDate} source={report?.sources.find((item) => item.lead_source_id === source.id)} />) : <EmptySourcesState reportDate={reportDate} />}</CardContent></Card>{typeof parameters.sucesso === "string" ? <p role="status" className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Origem salva com sucesso. Se aplicável, atualize as demais origens.</p> : null}{isComplete ? <div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex gap-3"><CheckCircle2 aria-hidden="true" className="mt-0.5 size-5 text-emerald-700" /><div><h2 className="font-bold text-emerald-950">Reporte concluído</h2><p className="mt-1 text-sm text-emerald-900">As origens ativas para este dia foram atualizadas.</p><Button asChild className="mt-4 min-h-11"><Link href="/dashboard">Voltar ao Dashboard</Link></Button></div></div></div> : null}</>}</div></div>;
}

function EmptySourcesState({ reportDate }: Readonly<{ reportDate: string }>) {
  return <div className="rounded-xl border border-dashed bg-muted/40 p-5" role="status"><h2 className="font-semibold">Nenhuma origem disponível para esta data.</h2><p className="mt-1 text-sm text-muted-foreground">Não há origens configuradas com vigência em {formatReportDate(reportDate)}. Escolha outra data ou solicite à agência a configuração de uma origem aplicável.</p></div>;
}

function SourceCard({ leadSource, reportDate, source }: Readonly<{ leadSource: LeadSource; reportDate: string; source: ReportSource | undefined }>) { const status: ReportSourceStatus = source?.status ?? "PENDING"; const variant = status === "FILLED" ? "success" : status === "NO_CONTACTS" ? "secondary" : "outline"; return <div className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{leadSource.name}</h2>{leadSource.isPrimary ? <Badge variant="secondary">Principal</Badge> : null}<Badge variant={variant}>{SOURCE_STATUS_LABEL[status]}</Badge></div>{status === "FILLED" && source ? <p className="mt-1 text-sm text-muted-foreground">{source.leads_received} leads • {source.sales} vendas</p> : status === "NO_CONTACTS" ? <p className="mt-1 text-sm text-muted-foreground">Métricas zeradas para esta data.</p> : <p className="mt-1 text-sm text-muted-foreground">Ainda não definida.</p>}</div><Button asChild variant={status === "PENDING" ? "default" : "outline"} className="min-h-11 shrink-0"><Link href={`/reportes?data=${reportDate}&origem=${leadSource.id}`}>{status === "PENDING" ? <><PlusCircle aria-hidden="true" className="mr-2 size-4" />Preencher</> : <><Pencil aria-hidden="true" className="mr-2 size-4" />Editar</>}</Link></Button></div>; }
